### ISSUE TITLE
Problem installing plugin

### ISSUE THREAD

**Issue by C-NERD** [liquidev/lintplus#12]
Hi i am having trouble installing the plugin. Especially at this step 
```You may also want to add this to your user/init.lua to enable automatic linting upon opening/saving a file:``` i can't find the file user/init.lua the closest thing to it is core/init.lua and when I do paste the code in it and try to run lite_xl i get an error from the text editor. Not only that when I symlinked the lintplus_nim.lua file i get an error about version number not being the same with the compiler's version number

**Comment by C-NERD** [comment]
And when I do alter the version number from the file to 2.0 no error appears but the plugin also doesn't seem to work anymore because there. No changes to the editor

**Comment by liquidev** [comment]
You can open this file using the `Core: Open User Module` command. If you're on Linux, this `user/init.lua` file is located in `~/.config/lite-xl`. I'm not sure about Windows, but the aforementioned command should take you to this file.

Please try pulling the latest commits from master, I've updated the `-- mod-version` comment there already to work with Lite XL 2.0.

**Comment by C-NERD** [comment]
ok thanks

**Comment by C-NERD** [comment]
And on the issue of the version number you only updated the ```-- mod-version``` for 'init.lua'  hence lite-xl still throws errors for lintplus_nim.lua and lintplus_rust.lua

**Comment by C-NERD** [comment]
The plugin works perfectly after converting `-- lite-xl 1.16` to `-- lite-xl 2.0`

**Comment by C-NERD** [comment]
Great job on the plugin

**Comment by liquidev** [comment]
Oh, right. I updated these as well, everything should work as expected now.
