### ISSUE TITLE
[Lite XL 2.0.2] Logs and JS files don't work in async mode

### ISSUE THREAD

**Issue by wereami** [liquidev/lintplus#13]
At first, I tried to rewrite the linter for JS, but it did not work in any way, and I thought that it was in synchronous mode (the plugin itself works, I checked it). When I try to open a JS file or simply open logs, it throws an error. In the first case, I attach a screenshot, in the second it just throws "Tried to add view to locked node". Most likely I made a mistake in the installation, but I can't say for sure.
![error](https://user-images.githubusercontent.com/88658695/133891738-0be8b1bc-6dfe-4f5b-99d1-69c7752bf67f.png)

**Comment by liquidev** [comment]
Can you show the source code of the linter?

**Comment by wereami** [comment]
I wrote it based on the JSHint standard linter and documentation, but, perhaps, due to lack of experience with Lua, I could mess up well.
```lua
-- mod-version:2

local lintplus = require "plugins.lintplus"

lintplus.add("jshint") {
  filename = "%.js$",
  procedure = {
    command = lintplus.command {
      "jshint", lintplus.args, lintplus.filename
    },
    interpreter = lintplus.interpreter {
      warning = "[^:]: line (%d+), col (%d+), ([^\n]+)",
      error = "[^:]: line (%d+), col (%d+), ([^\n]+)",
    }
  },
}
```

**Comment by liquidev** [comment]
You need to use `lintplus.args_command` if you want to use `lintplus.args`. See how it's done in luacheck:

https://github.com/liquidev/lintplus/blob/3813e3e985587086f35da9f449506a3c4d7e0696/lintplus_luacheck.lua#L17-L24

Once you get the linter to work, please send a pull request with it :)

**Comment by wereami** [comment]
Unfortunately, it still doesn't work :(

**Comment by jgmdev** [comment]
closing this since we now use the lite-xl `process` api and this should not apply anymore
