### ISSUE TITLE
Lintplus is not working in linux

### ISSUE THREAD

**Issue by sheetcoder** [liquidev/lintplus#22]
I am new to lint-xl and I am trying out your plugin. I want a linter for python and rust, and I have flake8 already installed in my system. I have cloned(`git clone`) this repo inside `~/.config/lite-xl/plugins/` and added 

```
local lintplus = require "plugins.lintplus"
lintplus.setup.lint_on_doc_load()
lintplus.setup.lint_on_doc_save()
```

to my `init.lua` file. But when I open my python and rust files, I see no linting? I tried `Lint+: Check` returns this error

>No linter available for the given filetype

`lite-xl : 2.0.5 appimage`

**Comment by jgmdev** [comment]
You have to copy language_python.lua and lintplus_rust.lua to `~/.config/lite-xl/plugins/`

**Comment by sheetcoder** [comment]
If I move language_python.lua to plugins folder then I loose the syntax highlighting of python files and doing Lint+:check gives nothing 


and if I move  lintplus_rust.lua and do Lint+:check it will give

> lint+/rust: /app/src/lib.rs: linter exited with signal -110 : Connection timed out at ~/.config/lite-xl/plugins/lintplus/init.lua:230

**Comment by liquidev** [comment]
Oh dear, it seems like the filename slipped past my review. The name of the file in the repo should be `lintplus_python.lua`, not `language_python.lua`.

**Comment by liquidev** [comment]
As for the other issue, I'm afraid I can't help because the code is currently maintained by jgmdev, and I haven't thoroughly inspected his changes.

**Comment by jgmdev** [comment]
it seems the issue is some checkers return the output to stdout instead of stderr will fix

**Comment by sheetcoder** [comment]
@jgmdev If it helps this I got from the logger

>  lint+/flake8: manage.py: linter exited with signal 137 at ~/.config/lite-xl/plugins/lintplus/init.lua:230

**Comment by jgmdev** [comment]
As shown on the screenshot below the python linter is working, I did saw some rendering issues with this plugin but that should be a subject for another issue.

![2022-04-18_14:48:37](https://user-images.githubusercontent.com/1702572/163858921-69a91b2c-cf7f-4d38-9c4a-3ca8823e5266.png)
