### ISSUE TITLE
build-liteipc.sh uses shell-specific functions not available in standard sh

### ISSUE THREAD

**Issue by Wazubaba** [liquidev/lintplus#4]
`pushd` and `popd` are shell-specific functions not available to standard `sh` itself, so possible solutions are to either require `bash` specifically in the shebang line or the better but sadly less elegant, replace them with `cd` calls to make it work in just about any shell. Otherwise it will require edits on any distro that doesn't switch `sh` to another shell, which still seems to be relatively common, unfortunately.

**Comment by liquidev** [comment]
Fixed in `caa44d3`.
