### ISSUE TITLE
Lint+ doesn't work on Windows

### ISSUE THREAD

**Issue by azb92** [liquidev/lintplus#8]
Hello!
Today I decided instead of Linter plugin to start using Lint+. But I'm experiencing some problems with it. 
When I try to lint something then I got this error:
![lintplus_error](https://user-images.githubusercontent.com/27897397/120201424-1914a680-c22e-11eb-9061-6141013a609a.png)

**Comment by liquidev** [comment]
That's my bad, I was porting some string escaping code over from Nim to Lua and forgot that Lua has `table.insert(t, x)` instead of `t.add(x)` :sweat_smile:

I pushed a fix for this, please let me know if it works.

**Comment by azb92** [comment]
Now no errors from the plugin side. But command Lint+:Check only opens cmd.exe for some time without any commands there. Nothing happens.  Maybe some problem from my side here

**Comment by liquidev** [comment]
That's a problem with Lua on Windows that I cannot fix directly. However, I created a library specifically to mitigate that, called `liteipc` - it's included in this repository's root. It brings some benefits to lint+, such as a proper non-blocking (async) mode. Follow the [instructions in the readme](https://github.com/liquidev/lintplus#asynchrony) if you want to try it out. I haven't tried using it on Windows though, so I guarantee no success.

I'll be able to fix this problem for good as soon as Lite XL's `dev` branch with a better process handling library gets merged into the `master` branch. Right now this is the best I could do.

**Comment by liquidev** [comment]
Also, the readme mentions a `build-liteipc.bat` file, which currently isn't present. You can follow the commands in `build-liteipc.sh`, they should be pretty similar on Windows except `ln -s` which is Linux-specific. Instead of that you can simply copy `./liteipc/target/release/liteipc.dll` to `./liteipc_native.dll`.

**Comment by liquidev** [comment]
@azb92 I just published release 0.1.1, maybe you can check if that works? It features a fix for synchronous mode, that might fix your issue.

**Comment by jgmdev** [comment]
Closing this as it may no longer be applicable do to the switch to lite-xl `process` api.
